#!/usr/bin/env perl
use Mojolicious::Lite;
use Nagplot::DataSource;
use Data::Dumper;

my $config = plugin 'Config';

get '/' => sub {
  my $self = shift;
  $self->redirect_to('/web');
};

get '/web' => sub {
  my $self = shift;
  $self->render('start');
};

get '/json/:command' => sub {
        my $self = shift;
#	print Dumper($self);
	my $ds = Nagplot::DataSource->new(config => $config->{DataSource} );
	if ( $self->stash('command') eq 'hosts' ) {
		$self->render_json([$ds->hosts]);
	} elsif ( $self->stash('command') eq 'services' ) {
		$self->render_json([$ds->services($self->param('host'))]);
	} elsif ( $self->stash('command') eq 'query_state' ) {
		$self->render_json([$ds->query_state($self->param('host'),$self->param('services'))]);
	} else {
		$self->render_json([]);
	}
};
app->start;
